### ISSUE TITLE
请根据现有思路安排计算工作

### ISSUE THREAD

**Issue by lujiaying** [BUPT-768/tianchi_project#4]
除了计算用户相似度外，还有什么需要大规模计算的任务？请分配给我

或者请把现有的思路分享一下。

**Comment by JayveeHe** [comment]
之前看了一篇豆瓣电影所参考的论文《The Wisedom of the Few》，讲的是基于专家评分的CF，思想就是“专家给出的评分可以比大众的更客观”，这样每次就不用计算各个用户对之间的相似度了，只需要计算某个用户与某个专家用户的相似度即可，减少了计算量。
我想我们能不能先选取浏览item数大于某个值的一批用户作为专家用户，建立一个向量，然后做做比较，看看结果？

**Comment by lujiaying** [comment]
刚刚算了一下，平均每个用户浏览物品291个，浏览物品数大于291个的用户有4942个。
感觉这样的话专家还是偏多，我下午试一下中位数

**Comment by JayveeHe** [comment]
嗯，或者找前百分之10之类的

**Comment by lujiaying** [comment]
- 根据用户的浏览物品数所得分析结果
  
  `count    10000.000000`
  
  `mean       471.900200`
  
  `std        607.096113`
  
  `median     287.000000`
  
  `min          1.000000`
  
  `25%        124.000000`
  
  `50%        287.000000`
  
  `75%        592.000000`
  
  `max      14368.000000`

update in: https://github.com/BUPT-768/tianchi_project/wiki
