### ISSUE TITLE
筛选正样本和负样本

### ISSUE THREAD

**Issue by lujiaying** [BUPT-768/tianchi_project#7]
**前29天**作为训练集
**最后1天**作为测试集

买过的物品作为正样本

没买过的作为负样本，正负样本数量相同。
因为负样本数量更多，所以随机取。

**Comment by lujiaying** [comment]
@JayveeHe 请把目前采用的正样本选取规则更新在此问题下。

另外，选择json保存和.csv保存结果，有什么优劣吗？
个人比较倾向于csv，结构单一，易于处理。

**Comment by JayveeHe** [comment]
正样本：对于18到19日一天之内有购买行为的用户，统计了一下有1575个用户
17-19日有购买行为的用户则为2724个
所以在这些用户所发生行为的item中选取18到19日有4的item，建立向量作为正样本
负样本则任意取没有购买的item建立向量（待斟酌）

**Comment by JayveeHe** [comment]
关于保存格式，如果是结构单一的数据用csv的确不错。
但是遇到有嵌套结构的数据则json更利于解析，并且可读性好，不过json的占用空间比较大。

我们可以在简单数据（单行）上使用csv，复杂数据（包含多种结构）上使用json

**Comment by lujiaying** [comment]
事实上，大部分的结果都可以转化为单行表示。

比如，样本结果集：
user_id, item_id, tag

处理json因为多了几层嵌套，逻辑上更复杂，处理也更慢
